/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.Random;
import java.util.Scanner;

public class App {

    public static Random random = new Random();
    public static int[] num_aleatorios = new int[(int)(Math.random()*(10-5)+5)];
    public static char[] cont_aleatorio = new char[(int)(Math.random()*(10-5)+5)];

    public static void main(String[] args) {
        try {
            //1
            Scanner teclado = new Scanner(System.in);
            int elemento_int;
            char elemento_char;
            int opcion;
            System.out.println("Tamaño: " + num_aleatorios.length);
            System.out.println("Tamaño: " + cont_aleatorio.length);
            do {
                
                System.out.println("1. Recorrer secuencialmente");
                System.out.println("2. Actualizar");
                System.out.println("3. Añadir");
                System.out.println("4. Borrar");
                System.out.println("5. Ordenar el vector");
                System.out.println("6. Búsqueda");
                System.out.println("7. Salir");

                opcion = teclado.nextInt();

                switch(opcion){

                    case 1:
                        Llenar_arreglos(); 
                        Recorrer_sec(true);
                            break;

                    case 2: 
                        Actualizar_int(1, 777);
                        Actualizar_char(2, 'Z');
                        Listar_arreglos();
                            break;

                    case 3: 
                        num_aleatorios = añadir_int(5);
                        cont_aleatorio = añadir_char('T');
                        Listar_arreglos();
                            break;

                    case 4: 
                        Borrar_int(2);
                        Borrar_char(1);
                        Listar_arreglos();
                            break;

                    case 5:
                        Ordenar_int_asc();
                        Ordenar_char_asc();
                        Listar_arreglos();

                        Ordenar_int_des();
                        Ordenar_char_des();
                        Listar_arreglos();
                            break;

                    case 6:
                        System.out.println("¿Qué elemento va a buscar del vector de numeros?");
                        elemento_int = teclado.nextInt();
                        System.out.println(Buscar_int(elemento_int));
                        System.out.println("¿Qué elemento va a buscar del vector de caracteres?");
                        elemento_char = teclado.next().charAt(0);
                        System.out.println(Buscar_char(elemento_char));
                            break;
                    
                    case 7: System.out.println("Finalizó");
                }
                
            } while(opcion!=7);

            //2
            System.out.println(Calcular_temp(1000));
            //3
            Ordenar_vector();
            //4
            System.out.println(eliminar_posicion((short)10));
            //5
            System.out.println(decimal_hexadecimal(540));
            //6
            matrices_cua_tra(3);
            //7
            System.out.println(producto_division(3));
            //8
            matriz_X_O();
            //9
            numeros_alea();
        } 

        catch (Exception e) {
            System.out.println("Ocurrió un error \n" + e);
        }

    }

    /*
     * 1. Implemente un programa en java donde inserte elementos en dos vectores
     * globales de tamaños aleatorios y de contenido aleatorio (uno numérico y otro
     * de Strings). Considere dejar espacios libres en los vectores.
     * 
     * Desde un menú en el programa principal debe considerar cada opción para
     * llamar las siguientes funciones que también debe programar:
     * 
     * a. Recorrer secuencialmente (recibe un true cuando va del primero al último y
     * un false cuando va del último al primero)
     * • De primer elemento a último elemento: Imprime desde el primer elemento
     * hasta el último del vector dado en el parámetro de entrada.
     * • De último elemento al primer elemento: Imprime desde el último elemento
     * hasta el primero del vector dado en el parámetro de entrada.
     * 
     * b. Actualizar: recibe la posición que va a actualizar y el elemento. Al final
     * imprime el vector actualizado.
     * 
     * c. Añadir: después del último: recibe el elemento que va a añadir. Al final
     * imprime el vector actualizado.
     * 
     * d. Borrar: Recibe la posición donde del elemento que va a borrar.
     * 
     * e. Ordenar el vector:
     * • Ascendentemente.
     * • Descendentemente.
     * 
     * f. Búsqueda: Recibe como parámetro el elemento a buscar y devuelve un String
     * separado por el carácter '-', mostrando las posiciones donde se encuentra el
     * elemento.
     */

    public static void Llenar_arreglos() throws Exception{
        try {
            char[] datos = {'A','B','C','D','E'};
            for(int i=0; i<=num_aleatorios.length-1; i++){
                num_aleatorios[i] = (int)(Math.random()*(100-1)+1);
            }

            for(int i=0; i<=cont_aleatorio.length-1; i++){
                cont_aleatorio[i] = datos[random.nextInt(datos.length)];
            }
        } 
        catch (Exception e) {
            throw new Exception(e); 
        }
    }

    public static void Recorrer_sec(boolean orden) throws Exception{
        try {
            String txt_inf_1 = "";
            String txt_inf_2 = "";
            if(orden==true){

                for(int i=0; i<=num_aleatorios.length-1; i++){
                    txt_inf_1 += num_aleatorios[i] + " ";
                }

                for(int i=0; i<=cont_aleatorio.length-1; i++){
                    txt_inf_2 += cont_aleatorio[i] + " ";
                }
                System.out.println(txt_inf_1);
                System.out.println(txt_inf_2);
            }

            else{
                for(int i=num_aleatorios.length-1; i>=0; i--){
                    txt_inf_1 += num_aleatorios[i] + " ";
                }

                for(int i=cont_aleatorio.length-1; i>=0; i--){
                    txt_inf_2 += cont_aleatorio[i] + " ";
                }
                System.out.println(txt_inf_1);
                System.out.println(txt_inf_2);
            }  
        } 
        catch (Exception e) {
            throw new Exception(e); 
        }
    }

    public static void Actualizar_int(int pos, int elem) throws Exception{
        try {
            num_aleatorios[pos] = elem;
        } 
        catch (Exception e) {
            throw new Exception(e); 
        }
    }

    public static void Actualizar_char(int pos, char elem) throws Exception{
        try {
            cont_aleatorio[pos] = elem;
        } 
        catch (Exception e) {
            throw new Exception(e); 
        }
    }

    public static int[] añadir_int(int elem_añad) throws Exception{
        try {
            int[] nuevoArray_int = new int[num_aleatorios.length + 1];

            for(int i=0; i<=num_aleatorios.length-1; i++){
                nuevoArray_int[i] = num_aleatorios[i];
            }
            nuevoArray_int[nuevoArray_int.length-1] = elem_añad;
            return nuevoArray_int;
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    }

    public static char[] añadir_char(char elem_añad) throws Exception{
        try {
            char[] nuevoArray_char = new char[cont_aleatorio.length + 1];

            for(int i=0; i<=cont_aleatorio.length-1; i++){
                nuevoArray_char[i] = cont_aleatorio[i];
            }
            nuevoArray_char[nuevoArray_char.length-1] = elem_añad;
            return nuevoArray_char;
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    }

    public static void Borrar_int(int pos_borrar) throws Exception{
        try {
            num_aleatorios[pos_borrar] = 0;
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    } 

    public static void Borrar_char(int pos_borrar) throws Exception{
        try {
            cont_aleatorio[pos_borrar] = ' ';
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    } 

    public static void Ordenar_int_asc() throws Exception{
        try {
            System.out.println("Numeros ordenados ascendentemente");
            for (int i=0; i<num_aleatorios.length - 1; i++) {
                for (int j=0; j<num_aleatorios.length - i - 1; j++) {
                    // Si el elemento actual es mayor que el siguiente, intercambiarlos
                    if (num_aleatorios[j]>num_aleatorios[j + 1]) {
                        // Intercambio de elementos
                        int temp = num_aleatorios[j];
                        num_aleatorios[j] = num_aleatorios[j + 1];
                        num_aleatorios[j + 1] = temp;
                    }
                }
            }
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    }
    public static void Ordenar_int_des() throws Exception{
        try {
            System.out.println("Numeros ordenados descendentemente");
            for (int i=0; i<num_aleatorios.length - 1; i++) {
                for (int j=0; j<num_aleatorios.length - i - 1; j++) {
                    // Si el elemento actual es mayor que el siguiente, intercambiarlos
                    if (num_aleatorios[j]<(num_aleatorios[j + 1])) {
                        // Intercambio de elementos
                        int temp = num_aleatorios[j];
                        num_aleatorios[j] = num_aleatorios[j + 1];
                        num_aleatorios[j + 1] = temp;
                    }
                }
            }
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    }

    public static void Ordenar_char_asc() throws Exception{
        try {
            System.out.println("Caracteres ordenados ascendentemente");
            for (int i=0; i<cont_aleatorio.length - 1; i++) {
                for (int j=0; j<cont_aleatorio.length - i - 1; j++) {
                    // Si el elemento actual es mayor que el siguiente, intercambiarlos
                    if (cont_aleatorio[j]>(cont_aleatorio[j + 1])) {
                        // Intercambio de elementos
                        char temp = cont_aleatorio[j];
                        cont_aleatorio[j] = cont_aleatorio[j + 1];
                        cont_aleatorio[j + 1] = temp;
                    }
                }
            }
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    }
    public static void Ordenar_char_des() throws Exception{
        try {
            System.out.println("Caracteres ordenados descendentemente");
            for (int i=0; i<cont_aleatorio.length - 1; i++) {
                for (int j=0; j<cont_aleatorio.length - i - 1; j++) {
                    // Si el elemento actual es mayor que el siguiente, intercambiarlos
                    if (cont_aleatorio[j]<(cont_aleatorio[j + 1])) {
                        // Intercambio de elementos
                        char temp = cont_aleatorio[j];
                        cont_aleatorio[j] = cont_aleatorio[j + 1];
                        cont_aleatorio[j + 1] = temp;
                    }
                }
            }
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    }

    public static String Buscar_int(int elem_bus) throws Exception{
        try {
            String posiciones = "";

            for(int i=0; i<=num_aleatorios.length-1; i++){
                if(elem_bus==num_aleatorios[i])
                    posiciones += i + " - ";
            }
            return posiciones;
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    }

    public static String Buscar_char(char elem_bus) throws Exception{
        try {
            String posiciones = "";

            for(int i=0; i<=cont_aleatorio.length-1; i++){
                if(elem_bus==cont_aleatorio[i])
                    posiciones += i + " - ";
            }
            return posiciones;
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    }

    public static void Listar_arreglos() throws Exception{
        try {
            for(int i=0; i<=num_aleatorios.length-1; i++){
                System.out.print(num_aleatorios[i] + " ");
            }
            System.out.println();
            for(int i=0; i<=cont_aleatorio.length-1; i++){
                System.out.print(cont_aleatorio[i] + " ");
            }
            System.out.println();
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    }

    /*
     * 2. Escriba un algoritmo que calcule aleatoriamente N temperaturas, las lleve
     * a un vector y luego calcule su media, cuántas temperaturas están por encima
     * de la media y cuántas por debajo.
     */

    public static String Calcular_temp(int N) throws Exception{
        try {
            double[] temperaturas = new double[N];
            double suma = 0, media = 0;
            int encimaMedia = 0, debajoMedia = 0;

            for(int i=0; i<=temperaturas.length-1; i++){
                temperaturas[i] = (int)(Math.random()*(100-0)+0);
                suma += temperaturas[i];
            }
            media = suma/N; 

            for(int i=0; i<=temperaturas.length-1; i++){
                if(temperaturas[i] > media) 
                        encimaMedia++;
                    else
                        debajoMedia++;
            }

            return "La media de las temperaturas es: " + media + "\nEstan por encima de la media: " + encimaMedia +
                    " temperaturas \nEstan por debajo de la media: " + debajoMedia + " temperaturas";
        } 
        catch (Exception e) {
            throw new Exception("Ocurrió un error \n" + e);
        }
    }

    /*
     * 3. Cargue un vector a partir de un archivo de palabras, con mínimo 10
     * palabras. Ordene el vector de manera ascendente y luego de forma descendente.
     * 
     * Escriba el vector inicial sin ordenar, los vectores ordenados.
     */

    public static void Ordenar_vector() throws Exception{
        try {
            String[] arc_vacio = {"vacio"};
            String[] v_palabras = new String[10];
            int index = 0;

            File ub_pala = new File("app\\build\\resources\\palabras.txt");
            FileReader arc_pala = new FileReader(ub_pala);
            BufferedReader bu_pala = new BufferedReader(arc_pala);

            String linea = bu_pala.readLine();

            if(linea==null)
                System.out.println("Archivo vacío");
            else{
                while(linea!=null){

                    v_palabras[index] = linea;
                    System.out.println(v_palabras[index] + "\n");
                    index++;

                    linea = bu_pala.readLine();
                }
            }
            ordenarAscendente(v_palabras);

            System.out.println("Vector ordenado ascendentemente");    
            for(int i=0; i<=v_palabras.length-1; i++){
                System.out.println(v_palabras[i]);
            }

            System.out.println(" ");

            ordenarDescendente(v_palabras);
            System.out.println("Vector ordenado descendentemente");
            for(int i=0; i<=v_palabras.length-1; i++){
                System.out.println(v_palabras[i]);
            }
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    }

    public static void ordenarAscendente(String[] vector) throws Exception{
        try {
            int n = vector.length;
            for (int i = 0; i < n - 1; i++) {
                for (int j = 0; j < n - i - 1; j++) {
                    // Si el elemento actual es mayor que el siguiente, intercambiarlos
                    if (vector[j].compareTo(vector[j + 1]) > 0) {
                        // Intercambio de elementos
                        String temp = vector[j];
                        vector[j] = vector[j + 1];
                        vector[j + 1] = temp;
                    }
                }
            }
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    }
    public static void ordenarDescendente(String[] vector) throws Exception{
        try {
            int n = vector.length;
            for (int i = 0; i < n - 1; i++) {
                for (int j = 0; j < n - i - 1; j++) {
                    // Si el elemento actual es mayor que el siguiente, intercambiarlos
                    if (vector[j].compareTo(vector[j + 1]) < 0) {
                        // Intercambio de elementos
                        String temp = vector[j];
                        vector[j] = vector[j + 1];
                        vector[j + 1] = temp;
                    }
                }
            }
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    }
    /*
     * 4. Escriba un algoritmo que cree un vector de N elementos (el N es dado por
     * el usuario) de números short aleatorios positivos mayores que cero, y luego
     * le pregunte al usuario qué posición quiere eliminar. Luego por un menú
     * presente las opciones: Dejar la casilla en 0 o desplazar los elementos de
     * manera que el cero quede en la última posición del vector. Después de la
     * operación mostrará el vector cómo va quedando y volverá a preguntar qué
     * posición quiere borrar y mostrará nuevamente el menú. En el menú aparecerá la
     * opción para terminar el programa.
     */

    public static String eliminar_posicion(short N) throws Exception{
        try {
            String txt_retornar = "";
            short posicion;
            short opcion;
            Scanner teclado = new Scanner(System.in);
            short[] num_alea = new short[N];

            for(short i=0; i<=num_alea.length-1; i++){
                num_alea[i] = (short)(Math.random()*100);
                System.out.println(i + ". " + num_alea[i]);
            }
            System.out.println("¿Qué posición desea eliminar?");
            posicion = teclado.nextShort(); 

            do {

                System.out.println("------Menu------\n");
                System.out.println("1. Dejar la casilla en 0\n");
                System.out.println("2. Desplazar los elementos\n");
                System.out.println("3. Mostrar");

                opcion = teclado.nextShort();

                switch (opcion){
                    case 1: num_alea[posicion] = 0;
                        break;

                    case 2: for(short i=posicion; i<=num_alea.length-1; i++){

                                    if(i==num_alea.length-1){
                                        num_alea[i] = 0;
                                    }
                                    else{
                                        num_alea[i] = num_alea[i+1];
                                    }
                            }
                        break;

                    case 3: System.out.println("Finaliza");
                        break;
                }   

            } while (opcion!=3);

            for(short i=0; i<=num_alea.length-1; i++){
                txt_retornar += (num_alea[i]) + "\n";
            }

            return txt_retornar;
        } 
        catch (Exception e) {
            throw new Exception("Ocurrió un error \n" + e);
        }
    }

    /*
     * 5. Escriba un algoritmo para convertir un número decimal en un número
     * hexadecimal, apoyado en vectores.
     */

    public static String decimal_hexadecimal(int num) throws Exception{
        try {
            char[] v_hexadecimal = {'0','1','2','3','4','5','6','7',
                                    '8','9','A','B','C','D','E','F'};
            String num_hexad = "";
            int resultado = num;
            int residuo;
           
            do{

                residuo = resultado % 16;
                num_hexad = String.valueOf(v_hexadecimal[residuo]) + num_hexad;
                resultado = resultado/16;
                System.out.println(residuo);

            }while(resultado!=0);

            return num_hexad;
        } 
        catch (Exception e) {
            throw new Exception("Ocurrió un error \n" + e);
        }
    }

    /*
     * 6. Escriba un algoritmo que solicite al usuario el orden de una matriz
     * cuadrática, implemente su matriz transpuesta (investiga qué es) y la imprima.
     */

    public static void matrices_cua_tra(int tam) throws Exception{
        try {
            int[][] m_cuadratica = new int[tam][tam];
            int[][] m_transpuesta = new int[tam][tam];
            Scanner teclado = new Scanner(System.in);
            String matriz = "";
            String transpuesta = "";

            for(int fil=0; fil<m_cuadratica.length; fil++){
                
                for(int col=0; col<m_cuadratica.length; col++){
                    System.out.println("Posicion [" + fil + "][" + col + "]:");
                    m_cuadratica[fil][col] = teclado.nextInt();
                    matriz += m_cuadratica[fil][col] + " ";
                }
                matriz += "\n";
            }
            System.out.println(matriz);

            for(int fil=0; fil<=m_transpuesta.length-1; fil++){

                for(int col=0; col<=m_transpuesta.length-1; col++){
                    m_transpuesta[fil][col] = m_cuadratica[col][fil];
                    transpuesta += m_transpuesta[fil][col] + " ";
                }
                transpuesta += "\n";
            }
            System.out.println(transpuesta);
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    }

    /*
     * 7. Escriba un algoritmo que calcule el producto y la división. Los operandos
     * serán la suma de elementos de la diagonal principal y la suma de los
     * elementos de la diagonal secundaria. Los elementos de la matriz deben ser
     * llenados usando la función random para calcular números aleatorios entre 10 y
     * 100.
     */

    public static String producto_division(int tam) throws Exception{
        try {
            int[][] m_random = new int[tam][tam];
            double suma_d_prin = 0;
            double suma_d_sec = 0;
            double producto;
            double division; 
            String matriz = ""; 

            for(int fil=0; fil<=m_random.length-1; fil++){

                for(int col=0; col<=m_random.length-1; col++){
                    m_random[fil][col] = (int)(Math.random()*(100-10)+10);

                    if(fil==col)
                        suma_d_prin += m_random[fil][col];
                    if(fil + col == tam-1)
                        suma_d_sec += m_random[fil][col];
                    
                    matriz += m_random[fil][col] + " ";
                }
                matriz += "\n";
            }
            System.out.println(matriz);
            producto = suma_d_prin * suma_d_sec;
            division = suma_d_prin / suma_d_sec;
            return "El producto de las diagonales es: " + producto + "\n" + "La división de las diagonales es: " + division;
        } 
        catch (Exception e) {
            throw new Exception("Ocurrió un error \n" + e);
        }
    }

    /*
     * 8. Escriba un algoritmo que llene de manera aleatoria una matriz de 100 filas
     * por 3 columnas con Xs y Os. Y mediante un vector cuente el número de Xs y Os
     * en cada fila. Imprima la matriz antes de llenarla, luego de llenarla y el
     * vector con el resultado.
     */

    public static void matriz_X_O () throws Exception{
        try {
            char m_X_O[][] = new char[100][3];
            int[] Contador_X = new int[100];
            int[] Contador_O = new int[100];
            int cuentaX = 0;
            int cuentaO = 0;
            String txt_ret = ""; 
            
            char[] datos = {'X','O'};

            //Imprimir matriz vacia
            for(int i=0; i<=m_X_O.length-1; i++){

                for(int j=0; j<=m_X_O[i].length-1; j++){
                    txt_ret += m_X_O[i][j] + " - ";
                }
                txt_ret += "\n";
            }
            System.out.println(txt_ret);

            txt_ret = "";

            //Llenar matriz con Xs y Os
            for(int i=0; i<=m_X_O.length-1; i++){

                for(int j=0; j<=m_X_O[i].length-1; j++){
                    m_X_O[i][j] = datos[random.nextInt(datos.length)];
                    txt_ret += m_X_O[i][j] + " ";
                }
                txt_ret += "\n";
            }

            //Contar Xs y Os y almacenar en vectores
            for(int i=0; i<=m_X_O.length-1; i++){

                for(int j=0; j<=m_X_O[i].length-1; j++){
                    if(m_X_O[i][j]=='X')
                        cuentaX++;
                    else if(m_X_O[i][j]=='O')
                        cuentaO++;
                }
                Contador_X[i] = cuentaX;
                Contador_O[i] = cuentaO;
                cuentaX = 0;
                cuentaO = 0;
            }
            System.out.println(txt_ret);

            //Imprimir los vectores
            for(int i=0; i<=Contador_X.length-1; i++){
                System.out.println("Fila " + (i + 1) + ": X=" + Contador_X[i] + ", O= " + Contador_O[i]);
            }
            //return "";
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    } 

    /*
     * 9. Llene una matriz de 5x5 con números aleatorios entre 1 y 9. En un vector
     * adicional, calcule la cantidad de números repetidos por cada fila y en otro
     * vector la cantidad de números repetidos de cada columna.
     */

    public static void numeros_alea() throws Exception{
        try {
            int[][] nume_alea = new int[5][5];
            int[] cant_rep_fil = new int[5];
            int[] cant_rep_col = new int[5];

            System.out.println("Matriz");
            for(int fil=0; fil<=nume_alea.length-1; fil++){

                for(int col=0; col<=nume_alea.length-1; col++){

                    nume_alea[fil][col] = (int)(Math.random()*(9-1)+1);
                }
            }
            for(int fil=0; fil<=nume_alea.length-1; fil++){

                for(int col=0; col<=nume_alea.length-1; col++){

                    System.out.print(nume_alea[fil][col] + "\t");
                }
                System.out.println();
            }
            System.out.println();

            System.out.println("Cantidad de repetidos por fila");
            for(int i=0; i<5; i++){
                cant_rep_fil[i] = contar_repetidos(nume_alea[i]);
            }
            for(int i=0; i<5; i++){
                System.out.print(cant_rep_fil[i] + "\t");
            }
            System.out.println();

            System.out.println("Cantidad de repetidos por columna");
            for(int col=0; col<5; col++){
                int[] columna = new int[5];

                for(int fil=0; fil<5; fil++){
                    columna[fil] = nume_alea[fil][col];
                }
                cant_rep_col[col] = contar_repetidos(columna);
            }
            for(int col=0; col<5; col++){
                System.out.print(cant_rep_col[col] + "\t");
            }
            System.out.println();
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    }

    public static int contar_repetidos(int[] v_repetidos) throws Exception{
        try {
            int repetidos = 0;

            for(int i=0; i<=v_repetidos.length-1; i++){

                for(int j=i+1; j<=v_repetidos.length-1; j++){
                    
                    if(v_repetidos[i] == v_repetidos[j])
                        repetidos++;
                        break;
                }
            }
            return repetidos; 
        } 
        catch (Exception e) {
            throw new Exception(e);
        }
    }
}
